version: '3'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
  shopsrus.api:
    image: shopsrus
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5026
    ports:
      - "5026:5026"
    depends_on:
      - mongodb

volumes:
  database-data:
